#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SIM.Resource", IsApplication=true)]

namespace SIM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int grow_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_down = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_from_left_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_from_left_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_from_up_down = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_from_up_up = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_right = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int slide_up = 2130968584;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050006
			public const int items_UOM = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int items_reason_codes = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int items_yes_no = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int location_areas = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int module_administration = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int module_inventory_management = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int module_lookups = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int module_main = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int module_reports = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int module_shipping_receiving = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int blue = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int blue_dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int blue_fb_bg = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int blue_light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int gray = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int gray_dark = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int gray_fb_bg = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int gray_light = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barcode_scanner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_blue_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_blue_bg_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_blue_bg_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_gray_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int circle_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int drawer_header_item = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int form_blue_button_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int form_login_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int glossy_bluewhite_without_border_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int glossy_white_with_border_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_collapse = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_expand = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_expand_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_ic_action_about = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_ic_drawer = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_new = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_overflow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_previous_item = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_search = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_submenu = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_add = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_administration = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_barcode_scanner = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_check_all = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_date_picker = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_delete = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_error = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_filter = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_inventory = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_launcher = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_lookups = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_print = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_refresh = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_search = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_shipping_receiving = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_uncheck_all = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int nav_bar_shadow = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int row_item_background = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int row_item_bg_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int row_item_bg_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int row_main_item_background = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int sim_edittext_background = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int sim_spinner_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int slide_down_blue_button_background = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int slide_up_gray_button_background = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int white_with_border_background = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0010
			public const int Quatity = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int Reason = 2131427345;
			
			// aapt resource value: 0x7f0b0043
			public const int action_settings = 2131427395;
			
			// aapt resource value: 0x7f0b0046
			public const int action_submenu = 2131427398;
			
			// aapt resource value: 0x7f0b0045
			public const int add_item = 2131427397;
			
			// aapt resource value: 0x7f0b0026
			public const int adjustment = 2131427366;
			
			// aapt resource value: 0x7f0b0013
			public const int adjustmentDetails = 2131427347;
			
			// aapt resource value: 0x7f0b0015
			public const int aid = 2131427349;
			
			// aapt resource value: 0x7f0b0018
			public const int aid_value = 2131427352;
			
			// aapt resource value: 0x7f0b0036
			public const int area = 2131427382;
			
			// aapt resource value: 0x7f0b0002
			public const int barcodeScannerButton = 2131427330;
			
			// aapt resource value: 0x7f0b002e
			public const int btnLogin = 2131427374;
			
			// aapt resource value: 0x7f0b0019
			public const int date = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int date_value = 2131427354;
			
			// aapt resource value: 0x7f0b0008
			public const int drawer_layout = 2131427336;
			
			// aapt resource value: 0x7f0b003f
			public const int expandButton = 2131427391;
			
			// aapt resource value: 0x7f0b001d
			public const int formHolder = 2131427357;
			
			// aapt resource value: 0x7f0b0009
			public const int frameLayout = 2131427337;
			
			// aapt resource value: 0x7f0b0020
			public const int fromDate = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int fromDateButton = 2131427361;
			
			// aapt resource value: 0x7f0b003b
			public const int genericText = 2131427387;
			
			// aapt resource value: 0x7f0b0031
			public const int imageButton1 = 2131427377;
			
			// aapt resource value: 0x7f0b0033
			public const int imageButton2 = 2131427379;
			
			// aapt resource value: 0x7f0b002f
			public const int imageButton_scanner = 2131427375;
			
			// aapt resource value: 0x7f0b0034
			public const int imageButton_slide_up = 2131427380;
			
			// aapt resource value: 0x7f0b0003
			public const int imagebutton0 = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int imagebutton1 = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int imagebutton2 = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int imagebutton3 = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int imagebutton4 = 2131427335;
			
			// aapt resource value: 0x7f0b000c
			public const int item = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int itemDescription = 2131427341;
			
			// aapt resource value: 0x7f0b0032
			public const int itemId = 2131427378;
			
			// aapt resource value: 0x7f0b0027
			public const int itemwithscan = 2131427367;
			
			// aapt resource value: 0x7f0b001f
			public const int labelFromdate = 2131427359;
			
			// aapt resource value: 0x7f0b0023
			public const int labelTodate = 2131427363;
			
			// aapt resource value: 0x7f0b003d
			public const int lblListHeader = 2131427389;
			
			// aapt resource value: 0x7f0b003e
			public const int lblListItem = 2131427390;
			
			// aapt resource value: 0x7f0b0038
			public const int left_drawer = 2131427384;
			
			// aapt resource value: 0x7f0b002b
			public const int lineSeperator = 2131427371;
			
			// aapt resource value: 0x7f0b002d
			public const int lineSeperator2 = 2131427373;
			
			// aapt resource value: 0x7f0b001e
			public const int linearFromDate = 2131427358;
			
			// aapt resource value: 0x7f0b0022
			public const int linearToDate = 2131427362;
			
			// aapt resource value: 0x7f0b001c
			public const int listview_added_item = 2131427356;
			
			// aapt resource value: 0x7f0b0035
			public const int locationName = 2131427381;
			
			// aapt resource value: 0x7f0b0029
			public const int loginFormBox = 2131427369;
			
			// aapt resource value: 0x7f0b000b
			public const int menu_ll = 2131427339;
			
			// aapt resource value: 0x7f0b0037
			public const int microSequence = 2131427383;
			
			// aapt resource value: 0x7f0b0047
			public const int option1 = 2131427399;
			
			// aapt resource value: 0x7f0b0048
			public const int option2 = 2131427400;
			
			// aapt resource value: 0x7f0b000f
			public const int packSize = 2131427343;
			
			// aapt resource value: 0x7f0b0028
			public const int relativeLayout1 = 2131427368;
			
			// aapt resource value: 0x7f0b000a
			public const int relative_layout_view_list = 2131427338;
			
			// aapt resource value: 0x7f0b0039
			public const int right_drawer = 2131427385;
			
			// aapt resource value: 0x7f0b003a
			public const int right_drawer_list = 2131427386;
			
			// aapt resource value: 0x7f0b0040
			public const int rowFirstTextView = 2131427392;
			
			// aapt resource value: 0x7f0b0041
			public const int rowSecondTextView = 2131427393;
			
			// aapt resource value: 0x7f0b0042
			public const int rowThirdTextView = 2131427394;
			
			// aapt resource value: 0x7f0b0012
			public const int saveButton = 2131427346;
			
			// aapt resource value: 0x7f0b0030
			public const int scanID = 2131427376;
			
			// aapt resource value: 0x7f0b0044
			public const int scan_item = 2131427396;
			
			// aapt resource value: 0x7f0b0001
			public const int searchButton = 2131427329;
			
			// aapt resource value: 0x7f0b000e
			public const int spinnerUOM = 2131427342;
			
			// aapt resource value: 0x7f0b0017
			public const int status = 2131427351;
			
			// aapt resource value: 0x7f0b001b
			public const int status_value = 2131427355;
			
			// aapt resource value: 0x7f0b003c
			public const int titleLayout = 2131427388;
			
			// aapt resource value: 0x7f0b0024
			public const int toDate = 2131427364;
			
			// aapt resource value: 0x7f0b0025
			public const int toDateButton = 2131427365;
			
			// aapt resource value: 0x7f0b0000
			public const int topIcons = 2131427328;
			
			// aapt resource value: 0x7f0b0014
			public const int user = 2131427348;
			
			// aapt resource value: 0x7f0b002a
			public const int userIDField = 2131427370;
			
			// aapt resource value: 0x7f0b002c
			public const int userPasswordField = 2131427372;
			
			// aapt resource value: 0x7f0b0016
			public const int user_value = 2131427350;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_barcode_result = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_drawer_menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_fragment_holder = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_inventory_adjustment_add_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_inventory_adjustment_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_inventory_adjustments_create = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_inventory_adjustments_filter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_sequencing_add_location = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int drawer_menu_left = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int drawer_menu_right = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int fragment_list_view = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int fragment_main_view = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int generic_layout_view = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int im_added_row_item = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int line_list_group = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int line_list_group_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int line_tem_list = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int right_list_drawer_item = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int row_item_2_liner = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int row_item_3_liner = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int row_listview = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int barcode_result = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int drawer_menu = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int inventory_adjustment_add_item = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int inventory_adjustment_update = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int inventory_adjustments_create = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int inventory_adjustments_filter = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int list_view = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int login = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int main = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int popup_menu = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int sequencing_add_location = 2131361802;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f08000f
			public const int action_add_item = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int action_create = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int action_delete = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int action_filter = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int action_no = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int action_save = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int action_settings = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int action_update = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int action_view = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int action_yes = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int application_name = 2131230730;
			
			// aapt resource value: 0x7f080027
			public const int confirm_delete_location = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int confirm_delete_location_title = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int confirm_save_inventory_adjustments = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int confirm_save_inventory_adjustments_title = 2131230760;
			
			// aapt resource value: 0x7f080002
			public const int hello_world = 2131230722;
			
			// aapt resource value: 0x7f080023
			public const int hint_Location = 2131230755;
			
			// aapt resource value: 0x7f08001d
			public const int hint_UOM = 2131230749;
			
			// aapt resource value: 0x7f080024
			public const int hint_area = 2131230756;
			
			// aapt resource value: 0x7f08001b
			public const int hint_item = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int hint_item_description = 2131230748;
			
			// aapt resource value: 0x7f080025
			public const int hint_micro_sequence = 2131230757;
			
			// aapt resource value: 0x7f08001f
			public const int hint_pack_quantity = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int hint_pack_reason = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int hint_pack_size = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int hint_select_UOM = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int hint_select_reason = 2131230754;
			
			// aapt resource value: 0x7f080017
			public const int label_adjustment_number = 2131230743;
			
			// aapt resource value: 0x7f080014
			public const int label_container = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int label_date = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int label_status = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int label_user = 2131230742;
			
			// aapt resource value: 0x7f080009
			public const int login_view_enter_your_password = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int login_view_enter_your_user_id = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int title_activity_asdmain = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int title_activity_barcode_result = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int title_activity_drawer_menu = 2131230725;
			
			// aapt resource value: 0x7f08001a
			public const int title_activity_inventory_adjustment_add_item = 2131230746;
			
			// aapt resource value: 0x7f08002a
			public const int title_activity_inventory_adjustment_update = 2131230762;
			
			// aapt resource value: 0x7f080019
			public const int title_activity_inventory_adjustments_create = 2131230745;
			
			// aapt resource value: 0x7f08002b
			public const int title_activity_inventory_adjustments_filter = 2131230763;
			
			// aapt resource value: 0x7f080004
			public const int title_activity_list_view = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int title_activity_login = 2131230727;
			
			// aapt resource value: 0x7f08002c
			public const int title_activity_sequencing_add_location = 2131230764;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppBaseTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int AppTheme = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int SIMActionBar = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int SIMEditTextStyle = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int SIMPopupMenu = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int SIMPopupMenu_textAppearanceLargePopupMenu = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int SIMPopupMenu_textAppearanceSmallPopupMenu = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int SIM_spinner_style = 2131296259;
			
			// aapt resource value: 0x7f090009
			public const int SpinnerItem_example = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int Theme_Transparent = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
